-- backend/DBRelated/create-table-db.sql
-- Kept for backwards compatibility. Prefer running the Node migration script:
--   npm run migrate
-- which executes DBRelated/schema.sql.
--
-- If you are inside the MySQL shell, you can still execute the schema directly:
--   SOURCE /absolute/path/to/backend/DBRelated/schema.sql;
--
-- The schema file contains idempotent CREATE/ALTER statements and will no longer
-- drop or truncate existing data.
