apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: votingapp-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - vote.techanalytics.org
    secretName: votingapp-tls
  rules:
  - host: vote.techanalytics.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: votingapp-frontend-service
            port:
              number: 3000