# .github/workflows/docker-build.yml
name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_FRONTEND: ghcr.io/${{ github.repository_owner }}/voting-frontend:latest
  IMAGE_BACKEND: ghcr.io/${{ github.repository_owner }}/voting-backend:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Normalize owner to lowercase
        id: owner
        run: echo "lc_owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GHCR with PAT
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.owner.outputs.lc_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            NEXT_PUBLIC_API_URL= 
          push: true
          tags: ghcr.io/${{ steps.owner.outputs.lc_owner }}/voting-frontend:latest

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.owner.outputs.lc_owner }}/voting-backend:latest
