# .github/workflows/deploy-backend.yml
name: Deploy Backend to Azure Web App - votebackend

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - ".github/workflows/main_votebackend.yml"
  workflow_dispatch:

concurrency:
  group: deploy-backend
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # (Optional) install & test just to catch issues early; runs inside backend/
      - name: Install deps (backend only)
        working-directory: backend
        run: npm ci

      - name: Run tests (if present)
        working-directory: backend
        run: npm test --if-present

      # Create a slim package of ONLY the backend app (exclude node_modules)
      - name: Archive backend
        run: |
          cd backend
          zip -r ../backend.zip . -x "node_modules/**"

      - name: Upload artifact (backend.zip)
        uses: actions/upload-artifact@v4
        with:
          name: backend-zip
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "votebackend"                                     # <-- your Web App name
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8576A084AC6E42298027ACA31933BA9E }}
          package: backend.zip
